### ISSUE TITLE
Why is miner showing constant blocks mined

### ISSUE THREAD

**Issue by faizann** [vincentchu/eth-private-net#8]
Hi
If this is a private network why any of the miners alice/bob/lily constantly keep printing these lines

```

INFO [10-01|00:24:18] Successfully sealed new block            number=313 hash=dc5479…7cc629
DEBUG[10-01|00:24:18] Trie cache stats after commit            misses=15 unloads=3
INFO [10-01|00:24:18] 🔗 block reached canonical chain          number=308 hash=2d8368…8d3cfe
INFO [10-01|00:24:18] 🔨 mined potential block                  number=313 hash=dc5479…7cc629
INFO [10-01|00:24:18] Commit new mining work                   number=314 txs=0 uncles=0 elapsed=271.092µs
```

**Comment by vincentchu** [comment]
Each node that is mining will print these lines out as new blocks are mined on the private network. These lines are the same ones that are printed if you were mining on the main Ethereum network.

**Comment by faizann** [comment]
Yeah but I am not doing any transactions. I thought mining happens when transactions are processed. Is it still supposed to be mining? The block numbers go up too constantly. I am probably wrong with my concepts here, my apologies for asking you wrong question.

**Comment by vincentchu** [comment]
The miners will continuously mine blocks (and be rewarded for doing so) even if there are no transactions to be processed. In a way, the reward for mining blocks provides an incentive for miners to provide an infrastructure which is "always on" and available for processing transactions. Miners will also get rewards for processing transactions (the "gas" that is spent on transactions and smart contracts goes to them).

**Comment by lm2a** [comment]
Hi, vincentchu, do you mean, miners are mining all the time, even empty blocks? And if true, makes it sense?
